baseURL = 'https://fd00.github.io/'
languageCode = 'en-us'
title = 'fd0.app'

theme = "LucentLink-Hugo"
minVersion = "0.115.0"

publishDir = "public"

[caches]
  [caches.images]
    dir = ':cacheDir/images'
